/*
 * This Jenkinsfile is to help this project build outside of GitHub Actions
 * where Jenkins can support different types of hardware and operating systems
 */

pipeline {
  agent none

  options {
    timeout(time: 4, unit: 'HOURS')
    buildDiscarder(logRotator(daysToKeepStr: '90'))
    disableConcurrentBuilds()
    timestamps()
  }
  stages {
    stage('Rust') {
      failFast true

      parallel {
        stage('Lint') {
          agent { label 'rust' }

          steps {
            sh 'cargo clippy'
          }
        }

        stage('Build') {
          agent { label 'rust' }

          steps {
            sh 'cargo build'
          }
        }

        stage('Test') {
          agent { label 'rust' }

          options {
            // This should help with flakey tests, like concurrency_local
            retry(1)
          }

          steps {
            sh 'cargo test'
          }
        }
      }
    }
  }
}

// vim: ft=groovy ts=2 sw=2 et
