/*
 * This Jenkinsfile is to help this project build outside of GitHub Actions
 * where Jenkins can support different types of hardware and operating systems
 */

pipeline {
  agent none

  options {
    timeout(time: 4, unit: 'HOURS')
    buildDiscarder(logRotator(daysToKeepStr: '90'))
    disableConcurrentBuilds()
    timestamps()
    // This should help with flakey tests, like concurrency_local
    retry(1)
  }

  stages {
    stage('Rust') {
      failFast true

      parallel {
        stage('Lint') {
          agent { label 'rust' }
          steps { sh 'cargo clippy' }
        }

        stage('Build') {
          agent { label 'rust' }
          steps { sh 'cargo build' }
        }

        stage('Arrow 57') {
          agent { label 'rust' }

          steps {
            sh 'cargo nextest r --features arrow-57'
            sh 'cargo test --doc'
          }
        }

        stage('Arrow 58') {
          agent { label 'rust' }

          steps {
            sh 'cargo nextest r --features arrow-58,nanosecond-timestamps'
            // It seems that cargo-nextest is not able to run doctests
            // <https://github.com/nextest-rs/nextest/issues/16>
            sh 'cargo test --doc'
          }
        }
      }
    }
    stage('Integration') {
      failFast true
      parallel {
        stage('delta-rs') {
          agent { label 'rust' }
          steps {
            withCredentials([gitUsernamePassword(credentialsId: 'gitea-token', gitToolName: 'Default')]) {
              sh './ci/integration-delta-rs.sh'
            }
          }
        }
        stage('deltalake Python') {
          agent { label 'rust && linux' }
          steps {
            withCredentials([gitUsernamePassword(credentialsId: 'gitea-token', gitToolName: 'Default')]) {
              sh './ci/integration-delta-rs.sh python'
            }
          }
        }
      }
    }
  }
}

// vim: ft=groovy ts=2 sw=2 et
